services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://watchtower:watchtower@watchtower-db:5432/watchtower
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      - db
    networks:
      - watchtower_net
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: watchtower-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: watchtower
      POSTGRES_PASSWORD: watchtower
      POSTGRES_DB: watchtower
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - watchtower_net

  ui:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - watchtower_net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  pgdata:

networks:
  watchtower_net:
    name: watchtower_net
    driver: bridge

